app = "login-senha-flask"

[build]
  image = "flyio/python:latest"  

[http_service]
  internal_port = 5000 
  force_https = true    
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0